
-- Create strategy_schedule_points table
CREATE TABLE public.strategy_schedule_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  strategy_id bigint NOT NULL REFERENCES public.strategy_snapshots(id) ON DELETE CASCADE,
  interval_index int4 NOT NULL,
  hour_index int4,
  target_action text NOT NULL CHECK (target_action IN ('charge', 'discharge', 'idle')),
  target_power_mw numeric(12,4) NOT NULL DEFAULT 0,
  charge_bid_price numeric(12,4),
  discharge_bid_price numeric(12,4),
  benchmark_price numeric(12,4),
  expected_soc_after numeric(12,4),
  expected_energy_mwh numeric(12,4),
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (strategy_id, interval_index)
);

-- Index on strategy_id
CREATE INDEX idx_strategy_schedule_points_strategy_id ON public.strategy_schedule_points(strategy_id);

-- RLS policies
ALTER TABLE public.strategy_schedule_points ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public can read strategy_schedule_points"
ON public.strategy_schedule_points FOR SELECT TO anon USING (true);

CREATE POLICY "public can insert strategy_schedule_points"
ON public.strategy_schedule_points FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "public can delete strategy_schedule_points"
ON public.strategy_schedule_points FOR DELETE TO anon USING (true);
