// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsbxkggbducdasbcpnrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzYnhrZ2diZHVjZGFzYmNwbnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4MzAzMTUsImV4cCI6MjA4OTQwNjMxNX0.e9kKsXw2enBj82HYiI6-N9Hv_X0X_pDu0NKynU-puuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});